### ISSUE TITLE
Cannot find module './module.js'

### ISSUE THREAD

**Issue by kayvanbree** [kyubisation/angular-server-side-configuration#1]
Hello! I'm trying to create a Docker container where you can just copy paste your build into, after which the environment variables automagically work. My plan is as follows.

# Express.js server

```javascript
const express = require('express');
const assc = require('angular-server-side-configuration');
const path = require('path');

const root = 'www';
const route = '/';
const app = express();

const dir = path.join(__dirname, root);

const envVariables = assc.EnvironmentVariablesConfiguration.searchEnvironmentVariables(root);

envVariables.insertAndSaveRecursively(root)
    .then(() => {
        app.use(route, express.static(root));

        app.listen(80, () => {
            console.log('Server running at http://localhost:80/');
        });
    });
```

The express server should serve all files underneath `/www`. Without the surrounding `.then()` and the `const assc = require('angular-server-side-configuration');`, this actually serves my `index.html` in the www folder. 

# Dockerfile

To make something that I can reuse, my plan was to just dump whatever Angular build into that `www` folder. For this to work I built this base `Dockerfile`:

```Dockerfile
FROM mhart/alpine-node:10

# Application lives in /src folder
WORKDIR /src

COPY package.json .
RUN npm install

COPY . .

EXPOSE 80

CMD ["npm", "start"]
```
This should start the server using the script `"start": "node server.js"`.

# The error

Now when I try and run the NodeJS server I get the following error: 

```
Cannot find module './module.js'
```

This error stems from the `main.js` file of the `angular-server-side-configuration` module:

```
"use strict";
require = require('esm')(module);
module.exports = require('./module.js');
```

Could it be that there is something missing in the latest version? Some dependency? Is there really a module called module.js?

**Comment by kayvanbree** [comment]
Looks like that file is indeed the culprit. It should be:

```javascript
"use strict";
require = require('esm')(module);
module.exports = require('./index.js');
``` 

In commit https://github.com/kyubisation/angular-server-side-configuration/commit/f79d40158b4c2482d9e861c3b79eee08872041fb#diff-8cfead41d88ad47d44509a8ab0a109ad the file was moved and `module.js` was removed. `module.js` used to be responsible for requiring `index.js`.

**Comment by kyubisation** [comment]
Yes, that is enough. This will search for all index.html in root recursively and insert the environment variables as an iife.
