### ISSUE TITLE
Breaks with Angular 7

### ISSUE THREAD

**Issue by kayvanbree** [kyubisation/angular-server-side-configuration#24]
Since our upgrade to Angular 7 `angular-server-side-configuration` stopped working. I was still at 0.2.0, so I'm trying to figure out if 1.2.1 fixes my problems (can't get it to work so far), but I was wondering if you have already tested 1.2.1 with Angular 7?

**Comment by kyubisation** [comment]
Yes, I have tested 1.2.1 with Angular 7 and with my test cases (and product from my company) it works.
What is the problem that you are currently having?

**Comment by kayvanbree** [comment]
Using the old version the IIFE function is still being inserted correctly. The following will be added to my head tag: 

```
<script>(function (self) {
    self.process = {
      "env": {
        "API_URL": "https://example.com/server",
        "WEBSOCKET_URL": "wss://example.com/server/websocket",
        "ENVIRONMENT": "develop"
      }
    };
  })(window)</script>
```

However somehow when Angular tries to use WEBSOCKET_URL it's filled with '/':

```
 main.bd0bb515985719b1f93d.js:1 Uncaught DOMException: Failed to construct 'WebSocket': The URL '/' is invalid.
    at t.create (https://webcalculatie.test.vanmeijel.eu:9443/main.bd0bb515985719b1f93d.js:1:2183240)
```

This is still weird because the default value in environment.prod.ts is ''

I'm still trying to figure out where the problem can be, but it's weird because the IIFE function is being inserted correctly..

**Comment by kyubisation** [comment]
Is WEBSOCKET_URL used in a forRoot or similar?
Does the insertion not work with 1.2.1?
Could you show me the code of the insertion?

**Comment by kayvanbree** [comment]
Yes, the WEBSOCKET_URL is used in forRoot:

```
const config = {
    websocketUrl: environment.socketUrl
}

@NgModule({
  imports: [
    EpgridModule.forRoot(epConfig),
  ],
  bootstrap: [AppComponent]
})
export class AppModule {}
```

I'm trying to figure out the insertion with 1.2.1, but my Docker image is broken on Windows machines, so I couldn't really test it well. I'll get back to you when I get the insertion to work with 1.2.1.

The old code for insertion is:

```
const assc = require('angular-server-side-configuration');

/**
 * Replace the deploy url
 */
function replaceDeployUrl(environment, baseHref) {
  console.log('Replacing deploy-url generated imports');
  const srcRegex = /(src=)(")(runtime|scripts|main|polyfills)/gm;
  const hrefRegex = /(href=)(")(styles)/gm;
  const replace = '$1$2' + baseHref + '$3';
  environment.regexReplace(srcRegex, replace);
  environment.regexReplace(hrefRegex, replace);
  return environment;
}

/**
 * Run everything
 */
function bootstrap() {
  let environment = assc.EnvironmentVariablesConfiguration
    .searchEnvironmentVariables(root);

  if (baseHref !== undefined) {
    environment = replaceDeployUrl(environment, baseHref);
    environment.replaceBaseHref(baseHref);
  }

  environment.insertAndSaveRecursively(root).then(() => {
    console.log('Done making Angular environment variable friendly!');
  });
}

let root = '/usr/share/nginx/html';
const baseHrefVariableName = 'BASE_HREF';
const baseHref = process.env[baseHrefVariableName];
bootstrap();
```

**Comment by kyubisation** [comment]
Did you compile your code with ngssc wrap-aot?
If used in forRoot (or any other AoT context), the ng build needs to be wrapped in `ngssc wrap-aot ng build ...` if you want to compile with AoT: https://www.npmjs.com/package/angular-server-side-configuration#wrap-aot

**Comment by kayvanbree** [comment]
I need to add environment variables after my build. I run angular-server-side-configuration on container startup, so that it uses the container's environment variables. It used to work. I do not want to create multiple builds per configuration...

**Comment by kyubisation** [comment]
ngssc wrap-aot merely preserves process.env... references through AoT compilation. It does not insert the environment variables.
It is not clear to me how this could have previously worked, since earlier versions of angular-server-side-configuration did not support this at all.

**Comment by kayvanbree** [comment]
Yeah that's weird. Maybe there was a deprecation that they only actually removed in Angular 7?

So the build pipeline should be something like this:

- Build using `ngssc wrap-aot`
- Create Docker container
- Run my script, inserting the environment variables

And then forRoot should work?

**Comment by kayvanbree** [comment]
I got it to work! Indeed, the only thing I needed to add was the wrapping. Thanks for your help!

**Comment by kyubisation** [comment]
No problem
Happy to help :-)
