### ISSUE TITLE
Functionality to change baseHref was removed?

### ISSUE THREAD

**Issue by kayvanbree** [kyubisation/angular-server-side-configuration#34]
In #9 I asked if there was a way to change the baseHref. Up until now I've always done that like this:

```
let config = new ngssc.EnvironmentVariablesConfiguration(); 
config.replaceBaseHref(baseHref);
```

This worked in v2.0.0, but somehow, in the changelog, it says:

```
# 2.0.0-beta.0 (2019-03-10)
---
### Breaking Changes

* Removed deprecated ProcessEnvConfiguration

# 1.3.0 (2019-03-09)

### Features
* Created ProcessEnvConfiguration, which will replace EnvironmentVariablesConfiguration
**### Deprecation
* EnvironmentVariablesConfiguration has been deprecated. Use ProcessEnvConfiguration insteadv**
```

Is there still a way to change de deployUrl? It looks like you can only use `ngssc insert` like this:

```
#!/bin/sh
ngssc insert /usr/share/nginx/html
nginx -g 'daemon off;'
```

I'm not familiar with Go, but it seems like there is no cli command to insert anything using regexes, is there (I only see a recursive and dry flag)?

**Comment by kayvanbree** [comment]
I can try to create this, but as I mentioned, I have never worked with Go. Would you like it to be a separate CLI command `ngssc deployurl /folder/`, or with a flag like `ngssc insert -deployUrl /folder/`?

**Comment by kyubisation** [comment]
Hm, I'd probably like it to be a value in the ngssc.json.
But I wonder if this could just be achieved with bash.
Would the following maybe work for you? (It's one line)
`find . -name '*.html' -exec sed -i -r "s/src=\"(runtime|scripts|main|polyfills)/src=\"$EP_SYSTEMX_BASE_HREF\1/g' {} \;`

**Comment by kayvanbree** [comment]
Thanks, that works after struggling with it for hours and finding out that it just didn't work because of my windows line endings. However, I did need to change another thing:

The deploy url can have `/` in it, so the delimiter of grep doesn't work for this:

```
find . -name '*.html' -exec sed -i -e "s~src=\"(runtime|scripts|main|polyfills)~src=\"$NGSSC_DEPLOY_URL\1~g" {} \;
```

I think this will do for our use case. Thanks for your help!

**Comment by kyubisation** [comment]
No problem 😃 
Sorry for removing this functionality, but I wanted to focus on the core functionality of this package and leave additional features to libraries or built-in functions that can handle this better.

**Comment by kayvanbree** [comment]
That's fine. By the way, if you want to run Angular through NGINX, I created a simple Docker image for it: https://github.com/kayvanbree/ngx-server-container.

**Comment by kyubisation** [comment]
Thanks! I'll certainly have a look at it.
