### ISSUE TITLE
No ngssc.json file generated

### ISSUE THREAD

**Issue by SirZach** [kyubisation/angular-server-side-configuration#37]
When I started setting this up in my app, I had just done a `npm install --save` instead of `ng add` since the article I was following was written before the updates were made to use the angular-cli schema. After reading the README, I did the `ng add` command and I followed the steps. I was confused later on in the README when it referenced the `ngssc.json` file that didn't exist in my repo. Luckily I was able to figure out that I needed to create that file.

I'm not sure if there was user-error on my part or if I encountered a bug. Just thought you would want to know. Thanks!

**Comment by kyubisation** [comment]
Hello @SirZach 
The ngssc.json in the source folder is no longer required, as the configuration has been moved into angular.json.
The ngssc.json in the output folder should be generated by the ngsscbuild builder (by executing `ng run yourprojectname:ngsscbuild:production`).

Maybe I need to indicate in the README that ngssc.json is generated.

**Comment by kyubisation** [comment]
I've updated the readme. Feel free to reopen the issue if it is still unclear or if you have any questions.

**Comment by SirZach** [comment]
Ok thanks for the update! I wasn't able to figure out how to pass the `filePattern` option to the `options` key in `angular.json` so I kept my own version of the `ngssc.json` which is working.

**Comment by kyubisation** [comment]
What version are you using?
Starting with Version 8 with the builder, I simply read the index html entry from the angular.json build target. `filePattern` should no longer be necessary.
Could you maybe explain your use-case?

**Comment by SirZach** [comment]
Yep, I am working on an old PHP app that has been migrated to Angular except for the `index.php` file so we don't have an `index.html`.

**Comment by kyubisation** [comment]
Ah, I see. I will add an additional option in the angular.json section.

**Comment by kyubisation** [comment]
Implemented in 8.2.1.
Feel free to reopen, if there is still something missing for your use-case.
