### ISSUE TITLE
Works wrong with aotSupport: true and more than 9 variables

### ISSUE THREAD

**Issue by phrixothrixa** [kyubisation/angular-server-side-configuration#38]
angular-server-side-configuration: 8.1.2
@angular/cli: 8.3.14
Operating System: Linux Mint 19.2

`untokenize` method of `TokenizeResult` works wrong if there are more than 9 environment variables, because of two of regexp (`new RegExp(`"${next.token}`, 'g')` and `new RegExp(`${next.token}`, 'g')`) matches fro token with `-1` (for example ngssc-token-1579518654990-1) anothers' tokens expression.

For example, for environment.prod.ts
`export const environment = {
  production: true,
  V1: process.env.V1 || 'v1',
  V2: process.env.V2 || 'v2',
  V3: process.env.V3 || 'v3',
  V4: process.env.V4 || 'v4',
  V5: process.env.V5 || 'v5',
  V6: process.env.V6 || 'v6',
  V7: process.env.V7 || 'v7',
  V8: process.env.V8 || 'v8',
  V9: process.env.V9 || 'v9',
  V10: process.env.V10 || 'v10',
  V11: process.env.V11 || 'v11',
  V12: process.env.V12 || 'v12',
  V13: process.env.V13 || 'v13',
};`

and generated temporary environment

`export const environment = {
  production: true,
  V1: "ngssc-token-1579518654990-5" as any,
  V2: "ngssc-token-1579518654990-6" as any,
  V3: "ngssc-token-1579518654990-7" as any,
  V4: "ngssc-token-1579518654990-8" as any,
  V5: "ngssc-token-1579518654990-9" as any,
  V6: "ngssc-token-1579518654990-10" as any,
  V7: "ngssc-token-1579518654990-11" as any,
  V8: "ngssc-token-1579518654990-12" as any,
  V9: "ngssc-token-1579518654990-13" as any,
  V10: "ngssc-token-1579518654990-1" as any,
  V11: "ngssc-token-1579518654990-2" as any,
  V12: "ngssc-token-1579518654990-3" as any,
  V13: "ngssc-token-1579518654990-4" as any,
};`

the output in main.bundle is:

`{production:!0,V1:process.env.V1 || 'v1',V2:process.env.V2 || 'v2',V3:process.env.V3 || 'v3',V4:process.env.V4 || 'v4',V5:process.env.V5 || 'v5',V6:(process.env.V10 || 'v10') + "0",V7:(process.env.V10 || 'v10') + "1",V8:(process.env.V10 || 'v10') + "2",V9:(process.env.V10 || 'v10') + "3",V10:process.env.V10 || 'v10',V11:process.env.V11 || 'v11',V12:process.env.V12 || 'v12',V13:process.env.V13 || 'v13'}`

The possible way is to rewrite `untokenize` with

`  untokenize(fileContent: string) {
    if (!this._variables.some(v => fileContent.includes(v.token))) {
      return fileContent;
    }

    return this._variables.reduce(
      (current, next) => current
        .replace(new RegExp(`"${next.token}"`, 'g'), next.expression)
        .replace(new RegExp(`"${next.token}[^0-9]`, 'g'), match => `(${next.expression}) + "${match[match.length - 1]}`)
        .replace(new RegExp(`${next.token}"`, 'g'), `" + (${next.expression})`)
        .replace(new RegExp(`${next.token}[^0-9]`, 'g'), match => `" + (${next.expression}) + "${match[match.length - 1]}`),
      fileContent);
  }`

Or to change `tokenize` method on `VariableTokenizer` class to avoid this collision. For example 
replace
`ngssc-token-${Date.now()}-${++this._tokenCounter}`
with
`ngssc-token-${++this._tokenCounter}-${Date.now()}`

**Comment by kyubisation** [comment]
Thanks for the feedback and the investigation. I will fix this as soon as possible.

**Comment by phrixothrixa** [comment]
@kyubisation I have one question. Can you explain or provide an example, why this lib need `aotSupport` flag? Maybe you discovered some cases when simple way like in this article https://pumpingco.de/blog/environment-variables-angular-docker/
doesn't work?

**Comment by kyubisation** [comment]
Yes. When using variables in an AoT context in Angular <= 8, the variables will be inlined with their build-time values. (This is no longer done with Ivy, i.e. Angular 9)

In the following example. during the build, environment.exampleStringValue will be replaced by the actual string value of environment.exampleStringValue during build time.
```ts
ExampleModule.forRoot(environment.exampleStringValue)

becomes (simplified)

ExampleModule.forRoot('example value')
```

Does that answer your question? Or did I misunderstand it?

**Comment by phrixothrixa** [comment]
Yes, now I understand! Thank you!
