### ISSUE TITLE
steps to use properly

### ISSUE THREAD

**Issue by guyisra** [kyubisation/angular-server-side-configuration#42]
I have somewhat mixed results with using this library, and I'm thinking I'm not using it properly

1.  does `npm run build:ngssc` replaces the normal build script or is it in addition to?
2. How do I use it locally (without docker) ? 
3. my current usage is :
in environment.ts set the env vars via process.env.something
and then in a component I would use environment.something but it always return undefined, so I'm missing some step of the process
4. how does `ng serve` works with this?

**Comment by kyubisation** [comment]
Hello @guyisra 

1. It replaces the normal build script, by wrapping the build step internally.
2. Build the app with `npm run build:ngssc` and run `ngssc insert` or `ngssc insert --recursive` in the output directory (download the ngssc binary from https://github.com/kyubisation/angular-server-side-configuration/releases/tag/v9.0.2).  Then start a webserver from the output directory or copy the output files to your webserver.
3. See my answer to 2. and 4.
4. At the current time, it does not. I have been thinking about providing a builder, but there was no need from consumers so far. If you would like to have this, I can put it on my backlog.

**Comment by guyisra** [comment]
thanks, So I should always use environment.something or using process.env.something throughout the app is ok?

also, should the ngssc binary work on a mac? I get an error but in docker (based on alpine) it works

**Comment by kyubisation** [comment]
The ngssc builder only scans the file defined in `ngsscEnvironmentFile` in the `ngssc` section of your angular.json file. So inside that file (default is environment.prod.ts, but you can also specify environment.ts) you can use process.env.NAME_OF_YOUR_VARIABLE and in other files, you can import the environment.ts file.
The ngssc_64bit binary should also work on OSX. If it does not, I can check if I can add an additional compilation target. Unfortunately I do not have a Mac to test it on.

To explain the process of ngssc:
1. `ng run your-project-name:ngsscbuild:production` is executed
2. The builder parses the file defined in `ngsscEnvironmentFile` for usages of `process.env.*`
3. The builder executes the build target defined in `browserTarget` defined in the `ngssc` section of your angular.json file (e.g. `"browserTarget": "your-project-name:build:production"` would execute the `build` target with the `production` configuration)
4. The builder generates the file `ngssc.json` in the output directory, containing the detected usages of `process.env.*`

As a separate step, `ngssc insert` is called:
1. `ngssc insert` is executed
2. The binary checks if `ngssc.json` is available or searches for all `ngssc.json` files with `--recursive`
3. The binary parses `ngssc.json` and reads the environment variable names and the pattern into which to insert these environment variables (default is the basename of the file defined in "index" of your angular.json build configuration, which is usually index.html)
4. The binary replaces `<!--CONFIG-->` in the index.html with the currently available environment variables

I hope this explains it a bit better.

**Comment by guyisra** [comment]
thanks again!
seems that just building main.go works without any special flags

**Comment by kyubisation** [comment]
@guyisra No problem 😃 
I just realized, there are currently no binaries for OSX. I will add these in a future release.
