### ISSUE TITLE
How can I pass arguments to the builder?

### ISSUE THREAD

**Issue by buehler** [kyubisation/angular-server-side-configuration#47]
Hey @kyubisation 

I'm currently using ngssc in combination with another builder (custom webpack build).

Now in my build pipeline, I'd like to build the application with the `--base-href URL` flag. With the given configuration of ngssc, this is not possible, since the builder throws `unknown option --base-href` at me.

Do you have any suggestion on how to use the ngssc build in conjunction with the `--base-href` flag?

Regards
Chris

**Comment by kyubisation** [comment]
If I understand you correctly, you would like to run `ng run ngsscbuild:production --base-href /something/`? Unfortunately this is not directly supported, as I did not want to duplicate the default "build" builder options (to not increase the complexity as a simple wrapper around the "normal" build and to allow other custom builders). Currently you would have to create a separate configuration in the "build" section.

e.g. angular.json
```json
...
  "projects": {
    "your-project": {
      ...
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            ...
          },
          "configurations": {
            "production": {
              ...
            },
            "custom-base-href": {
              ... same options as in production
              "baseHref": "/something/"
            },
          }
        },
        "ngsscbuild": {
          "builder": "angular-server-side-configuration:ngsscbuild",
          "options": {
            ...
          },
          "configurations": {
            "production": {
              "browserTarget": "your-project:build:production"
            },
            "custom-base-href": {
              "browserTarget": "your-project:build:custom-base-href"
            },
          }
        }
      }
    }
  }
...
```

And run this with `ng run your-project:ngsscbuild:custom-base-href`.

Would this work for your use case?

**Comment by buehler** [comment]
Thanks for the fast answer!

Mhmm just thinking about it... I _could_ set the base href in production as well I presume?

For now I guess this will suffice the case.
I'll test this aproach, thanks for the hints :-)

**Comment by kyubisation** [comment]
No problem 😃 

Yes, if the base-href is the one you need for production you can just as well configure it in the "production" configuration. In that case you would not need the "custom-base-href" configuration(s).

Feel free to reopen or create a new issue, if you encounter any problem.
