### ISSUE TITLE
How to set the output path of the ngssc builder?

### ISSUE THREAD

**Issue by maxiaolin9495** [kyubisation/angular-server-side-configuration#53]
Hi, 

thanks a lot for your work, i'm feeling a bit confused, when i tried to adjust the output path of the ngssc builder. 

As i use docker container to start my angular frontend, i tried to build the dist by the following RUN commend.

`RUN npm run build:ngssc --prod --output-path /dist` 

and what i received is the following error 

> frontend@0.0.0 build:ngssc /app
> ng run frontend:ngsscbuild:production "/dist"
>Unknown option: '/dist'
>npm ERR! code ELIFECYCLE
>npm ERR! errno 1
>npm ERR! frontend@0.0.0 build:ngssc: `ng run frontend:ngsscbuild:production "/dist"`
>npm ERR! Exit status 1
>npm ERR! 
>npm ERR! Failed at the frontend@0.0.0 build:ngssc script.
>npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Is it possible to configure the output path? If no, where is its default path

Best
Xiaolin

**Comment by kyubisation** [comment]
ngsscbuild wraps the ng build execution. While passing arguments should work (maybe with a =, e.g. `--output-path=/dist`), I would recommend adapting your angular.json build production configuration.

**Comment by maxiaolin9495** [comment]
With the adjust in angular.json works. :D Thanks

**Comment by kyubisation** [comment]
Feel free to reopen the issue, if you have another problem.
