### ISSUE TITLE
Problem when using CSP

### ISSUE THREAD

**Issue by Langstra** [kyubisation/angular-server-side-configuration#64]
We configured quite a strict CSP in nginx for our application. However, as ngssc inserts the environment variables as an inline script in the index.html this gives the following error.
```
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src-elem 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-Z1paUeSQdtR/lnsvS7jsLGBv4sX3iLd7TjkENuYj3+g='), or a nonce ('nonce-...') is required to enable inline execution.
```
We are unsure what a good solution would be. Basically we'd rather not loosen our CSP. A good solution to me would be crypographic hashing as described in the error message. NGSSC could after inserting the environment variables in the index.html also set an additional nginx header. I think this cannot be done in the index.html since nginx already set this header. (and also would be a potential security problem since an attacker could just as well insert the hash there)

**Comment by kyubisation** [comment]
My understanding of CSP is superficial, so I will have to do some research on this.
Since my time is currently fairly limited, I cannot yet promise any timeline for this.

**Comment by Langstra** [comment]
Thanks for your response. I'll be patient ;)

**Comment by kyubisation** [comment]
Can you maybe share part of your nginx configuration, where you specify the CSP?
I'm not yet quite sure what would be the best option, but maybe I can add a command to the CLI to generate a hash or nonce to insert into the nginx configuration either manually or automatically.

**Comment by Langstra** [comment]
```
location / {
    ....
    add_header Content-Security-Policy "object-src 'none'; script-src 'self'; script-src-elem 'self'; base-uri 'self'; require-trusted-types-for 'script'" always;
    ....
}
```

**Comment by jgoelten** [comment]
I'm currently facing the same issue as @Langstra . Loosing the major CSP security while enabling `unsafe-inline` in `script-src` is not an option for me. The NG_ENV environment variables are injected at runtime during the container's startup which makes it pretty hard or even impossible to pre-generate a valid hash. In my case the resulting script hash can only be evaluated after the application is actually beeing deployed on the target environment. In that case the browser tells me the hash for free but results in a short downtime and manual CD adjustments 🙈 Somehow this issue must be solved in a fully automated CI/CD approach. Looking forward :-)

**Comment by kyubisation** [comment]
It should be easy to implement a CLI function to generate the hash from the inline script.
The question is: should this be inserted into the nginx conf by the CLI tool or by yourself with a script?

**Comment by kyubisation** [comment]
I'm planning to add a CLI command `substitute`:

```
Substitutes the variable ${NGSSC_CSP_HASH} in files ending with ".template"
and copies the file while removing the ".template" extension.
${NGSSC_CSP_HASH} represents the CSP hash value of the IIFE generated/inserted by the
insert command.

By default looks for "*.template" files in the current working directory. Specify another
directory to search for "*.template" files via argument.
(e.g. `ngssc substitute /path/to/template/files`)

When applying the variable(s), the file is copied to the same directory without the
".template" extension with the substituion applied.
(e.g. `ngssc substitute`: /a/my.conf.template => /a/my.conf)

Use the "--out" flag to define a different output directory.
(e.g. `ngssc substitute --out=/b`: /a/my.conf.template => /b/my.conf)

Optionally supports substituting environment variables with the --include-env flag.
The format ${EXAMPLE} must be used ($EXAMPLE will not work). Additionally only
alphanumeric characters and _ are allowed as variable names (e.g. ${EXAMPLE_KEY}).
(e.g. `ngssc substitute --include-env`)
```

@Langstra, @jgoelten: Would that work for your use cases?

**Comment by Langstra** [comment]
I believe that would work just fine for us.
