### ISSUE TITLE
The library only works with CSP headers script-src unsafe-inline

### ISSUE THREAD

**Issue by k-genov** [kyubisation/angular-server-side-configuration#74]
The Content Security Policy headers are set from a web server and help browsers to prevent XSS attacks.

Unfortunately, this library only works with following setting: `script-src 'self' 'unsafe-inline'`. This basically disables the main use case for the CSP headers.
https://content-security-policy.com/unsafe-inline/

Angular, for instance, does not force the applications use to unsafe-inline for script-src.
https://angular.io/guide/security#content-security-policy

![image](https://user-images.githubusercontent.com/62137624/223452036-e645c98a-8d4b-46a8-8005-6423d7712404.png)

Is there a way to avoid using unsafe-inline for script-src?

**Comment by kyubisation** [comment]
Hello @k-genov 

See #64 and https://github.com/kyubisation/angular-server-side-configuration#ngssc-substitute
