### ISSUE TITLE
A way to change deploy url

### ISSUE THREAD

**Issue by kayvanbree** [kyubisation/angular-server-side-configuration#9]
In my project, the assets of one of the Angular applications are served under a subfolder, just like the application itself. The application can be found under `www.example.com/systemx`, because `www.example.com` is already home of another application. I want to be able to change the `/systemx` part dynamically, but if I only change the `base-href`, the assets still live under the root `/` according to the application. The root is routed to another container, so the calls to my assets yield a 404 error. 

I don't know if this is at all possible. I searched the files for `deploy` and `url`, but I found nothing to replace. Could this be done using a IIFE? I would do it myself, but I really have no clue where to start.

**Comment by kyubisation** [comment]
I'll have a look.
Could you specify what value you use for base-href?

**Comment by kayvanbree** [comment]
To get the baseHref I use `const baseHref = process.env['EP_SYSTEMX_BASE_HREF'];`, which is `/systemx/`

**Comment by kyubisation** [comment]
Looking at the resulting index.html with deployUrl set to https://example.com/, will generate `<script type="text/javascript" src="https://example.com/runtime.fc2e7968bd7a528e943c.js">`.
My recommendation would be to not use deployUrl, which will generate script tags which respect the base href.
If that is not an option, you could also the the EnvironmentVariablesConfiguration.prototype.regexReplace to replace /https:\/\/example.com\//g with "https://example.com/systemx/".

**Comment by kayvanbree** [comment]
Trying that right now. Maybe I can create a pull request if it works.

**Comment by kayvanbree** [comment]
I got my scripts to load from the correct location (so the deploy-url part works now). My complete environment still doesn't work completely, but I'll have to work on something else for now. What I did was use a regex on `src="runtime` etc and replace the `"` with `"/systemx/`:

```javascript
  const srcRegex = /(src=)(")(runtime|scripts|main|polyfills)/gm;
  const hrefRegex = /(href=)(")(styles)/gm;
  const replace = '$1$2' + baseHref + '$3';
  environment.regexReplace(srcRegex, replace);
  environment.regexReplace(hrefRegex, replace);
```

When I get everything working I'll create a pull request adding the functionality to the library.

**Comment by kyubisation** [comment]
This is very strange. Because scripts src respects base-href.
So, if you have
`<base href="/systemx/"><script src="runtime.js"></script>`
this will resolve to `https://host.com/systemx/runtime.js`.

**Comment by kayvanbree** [comment]
The BASE_HREF env is `/systemx/`, which results in `<script src="/systemx/runtime.js"></script>` if I use the code above.

**Comment by kyubisation** [comment]
I think we have a bit of a misunderstanding. Could you show me your index.html after base-href has been changed but before the regex replacement has been applied?

**Comment by kayvanbree** [comment]
```javascript
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>SystemX</title>
  <base href="/systemx/">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <script>(function(self){self.process={"env":{"ENV1":"...","ENVIRONMENT":"test"}};})(window)</script>
<link rel="stylesheet" href="styles.7828a0369a4dbe66b5ed.css"></head>
<body>
  <app-root></app-root>
<script type="text/javascript" src="runtime.a66f828dca56eeb90e02.js"></script><script type="text/javascript" src="polyfills.c66c767397f56fe9e39d.js"></script><script type="text/javascript" src="scripts.b6f869d9eeddcf8a6a95.js"></script><script type="text/javascript" src="main.c095f9a95b5674cd54af.js"></script></body>
</html>
```
Were you expecting it would be `src="http://host.com/runtime.js`? By the way, the BASE_HREF environment variable is not placed in the IIFE funtion. Is that by design or is something going wrong?

**Comment by kyubisation** [comment]
I just realized I did not answer your question.
If you use searchEnvironmentVariables the IIFE will only contain environment variables used in your code (by looking for process.env.* usages).
So, if process.env.BASE_HREF has been used in your code, it should be contained in the IIFE. If that is not the case, then it won't.

**Comment by kayvanbree** [comment]
Just finally got Jenkins to play along and everything works. I'll create a pull request now.

**Comment by kayvanbree** [comment]
Created https://github.com/kyubisation/angular-server-side-configuration/pull/10

**Comment by kayvanbree** [comment]
I think this can be closed
